version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - kojiro-yamashiro
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 0"
  - dependency-name: sprockets
    versions:
    - ">= 0"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
    - 1.8.9
  - dependency-name: webdrivers
    versions:
    - 4.5.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: ffi
    versions:
    - 1.14.2
  - dependency-name: capybara
    versions:
    - 3.34.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - kojiro-yamashiro
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 0"
