version: 1
update_configs:
  # Checks for Ruby:bundler updates weekly.
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    version_requirement_updates: "auto"
    default_assignees:
      - "kojiro-yamashiro"
    allowed_updates:
      - match:
          update_type: "all"
    ignored_updates:
          - match:
              dependency_name: "sprockets"
          - match:
              dependency_name: "ruby"

  # Checks for Dockerfile updates weekly.
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_assignees:
      - "kojiro-yamashiro"
    allowed_updates:
      - match:
          update_type: "all"
    ignored_updates:
          - match:
              dependency_name: "ruby"

# https://dev.classmethod.jp/articles/dependabot-101/
# https://gitlab.com/connorshea/vglist/-/blob/master/.dependabot/config.yml